// @generated — do not edit by hand.
// Regenerate with: BLESS_GLOSSARY=1 cargo test -p autonoetic-gateway bless_constitution_glossary
// Source of truth: the configured constitution markdown (see constitution_glossary.rs).
pub(crate) static GLOSSARY: &[(&str, &str)] = &[
    ("P-1.1", "Every tool call matches a declared capability"),
    ("P-1.10", "Missing capability returns permission error, never advisory."),
    ("P-1.11", "Unknown tool names deny by default (not silent-allow)."),
    ("P-1.2", "High-risk capabilities (`NetworkAccess`, `CodeExecution`, `AgentSpawn`) reject bare-string shorthand"),
    ("P-1.3", "Only agents holding `AgentRevision` may promote revisions."),
    ("P-1.4", "`ReadAccess` / `WriteAccess` scopes are enforced by glob match."),
    ("P-1.5", "`NetworkAccess` is scoped by host allowlist."),
    ("P-1.6", "`SandboxFunctions` applies to MCP tools only"),
    ("P-1.7", "`AgentSpawn.max_children` bounds concurrent spawns."),
    ("P-1.8", "`CredentialAccess` is scoped by service pattern."),
    ("P-1.9", "`CodeExecution` patterns match against command strings."),
    ("P-10.1", "Remote agents authenticate via Bearer token."),
    ("P-10.2", "Content API is exposed over HTTP for remote content access."),
    ("P-10.3", "JSON-RPC ingress requires `AUTONOETIC_SHARED_SECRET`."),
    ("P-10.4", "Remote agents inherit all approval gates."),
    ("P-10.5", "Layer mounts in remote execution are fetched and cached before sandbox use."),
    ("P-10.6", "OFP federated exchanges preserve cross-gateway causal context"),
    ("P-10.7", "No agent may resolve its own gate requests, whether directly or via a delegated agent it spawned."),
    ("P-10.8", "Shared-secret comparison is constant-time."),
    ("P-10.9", "Every gateway publishes a `constitution_digest` — SHA-256 over the canonical constitution text plus its rule-ID-to-enforcement-citation table."),
    ("P-11.1", "Parent → child messages route through `agent_spawn`."),
    ("P-11.2", "Child `clarification_needed` status returns as a tool result"),
    ("P-11.3", "`agent_message` is peer-to-peer between active sessions."),
    ("P-11.4", "Messages auto-inject into the target session at turn start."),
    ("P-11.5", "`agent_message` respects `policy.can_message_agent` ACL."),
    ("P-11.6", "Spawned children inherit `root_session_id` from parent."),
    ("P-11.7", "`max_children` is enforced at spawn."),
    ("P-11.8", "Spawn payload is preserved across approval and continuation."),
    ("P-2.1", "Remote network access across all networked tools (`sandbox_exec`, `credential.*`, `web.*`) is statically detected and blocks pending approval via the unified `GateService` (`GateKind::Approval`) rather than hard-denying."),
    ("P-2.10", "Gate-suspended turns (approval, user interaction, escalation) checkpoint via `YieldReason` and resume through `resume_from_checkpoint`."),
    ("P-2.11", "Suspended turns exceeding timeout mark the task failed while preserving continuation for explicit operator-driven resume."),
    ("P-2.12", "Deciders (human operators, autonomous reviewer agents, or policy engines) approve/reject gates via the approval resolution API."),
    ("P-2.13", "`user_ask` creates a gate via `GateService` with `GateKind::UserInput` and checkpoints the session as `YieldReason::UserInputRequired`."),
    ("P-2.14", "`user_ask` is refused if the workflow has active children or pending gates (approvals, escalations, or other `user_ask` interactions)."),
    ("P-2.15", "Spawn payload is preserved verbatim across approval resume."),
    ("P-2.16", "Promotion of revision N computes `cap_set(N) \\ cap_set(N-1)`."),
    ("P-2.17", "The auditor and evaluator backing a promotion must be **distinct agent identities** (not merely distinct sessions of the same agent)."),
    ("P-2.18", "All execution suspension points awaiting external input (approvals, user interactions, escalations) use the unified `GateService`."),
    ("P-2.19", "Gate enrichment messages (`gate_messages`) are append-only and recorded on the causal chain."),
    ("P-2.2", "Approval requests are persisted with unique IDs."),
    ("P-2.20", "Agents acting as gate deciders require the `GateDecider` capability."),
    ("P-2.21", "When an agent-decider cannot determine whether to approve or reject a gate (insufficient context, policy ambiguity, or high-risk action beyond its scope), it must escalate to a human operator rather than reject."),
    ("P-2.22", "When a revision carries federation-role verdicts, promotion runs the **FullJury** gate"),
    ("P-2.23", "Session approval grants expire after a configured TTL"),
    ("P-2.24", "Operator approval hardening on high-risk gates"),
    ("P-2.3", "Identical operations within a session deduplicate."),
    ("P-2.4", "Approved hosts auto-approve subsequent calls within the root session."),
    ("P-2.5", "Approval response surfaces `detected_hosts` for operator visibility."),
    ("P-2.6", "Fingerprint-identical approved executions skip re-approval for the gateway lifetime."),
    ("P-2.7", "Only concrete targets (URLs, IPs) cache"),
    ("P-2.8", "High-risk promotion requires evaluator AND auditor pass."),
    ("P-2.9", "`promotion_record` with `pass=true` rejects on error/critical findings, and on warning findings lacking evidence."),
    ("P-3.1", "Sandboxes default to `--unshare-all` — no network, no PID namespace."),
    ("P-3.10", "Promotion-gate execution (sealed evaluator / auditor runs) is denied network access regardless of the candidate's declared `NetworkAccess`."),
    ("P-3.2", "`--share-net` is set only when `NetworkAccess` is declared."),
    ("P-3.3", "Script-mode sandbox execution uses identical isolation policy."),
    ("P-3.4", "SDK bridge paths from inside the sandbox are relative-only, no traversal."),
    ("P-3.5", "Network errors inside the sandbox (URLError, ConnectionError, DNS) are detected and returned as tool failure."),
    ("P-3.6", "Layer mounts are read-only."),
    ("P-3.7", "Sandboxes enforce CPU/memory/PID/disk quotas."),
    ("P-3.8", "Destructive commands (`sudo`, `rm -rf`, `dd`, `mkfs`, shell injection) are blocked before sandbox creation."),
    ("P-3.9", "Dependency-manager package names are restricted to safe alphanumerics."),
    ("P-4.1", "Secrets never enter agent context"),
    ("P-4.10", "Refresh tokens live in vault, never exposed to agents."),
    ("P-4.11", "`credential_refresh` 401 auto-retry fires at most once per request."),
    ("P-4.12", "Secret-shaped text in responses is blocked by `prohibited_text_patterns`."),
    ("P-4.13", "Logs, traces, digests, and LLM prompts are redacted via `redact_text_for_logs` before storage."),
    ("P-4.14", "Redaction happens **before** causal-chain append (ordering invariant)."),
    ("P-4.15", "The gateway probes vault master-key presence at startup and emits a causal event recording the result."),
    ("P-4.2", "Vault uses AES-256-GCM with a random 96-bit nonce per entry."),
    ("P-4.3", "Master key is required from `AUTONOETIC_VAULT_KEY` or `AUTONOETIC_VAULT_KEY_PATH`"),
    ("P-4.4", "Credential IDs (`cred_*`) are mechanical references, never secret material."),
    ("P-4.5", "`credential_request` requires `CredentialAccess` matching the service."),
    ("P-4.6", "`credential_setup` `user_prompt` step suspends the session for operator approval."),
    ("P-4.7", "`credential_request` response is redacted"),
    ("P-4.8", "Secrets are zeroized from memory after injection."),
    ("P-4.9", "`credential_env` passes secrets as env vars resolved server-side."),
    ("P-5.1", "Messages to child agents pass `io.accepts` enforcement at ingress."),
    ("P-5.10", "`artifact_inspect` accepts explicit `art_*` IDs only"),
    ("P-5.11", "Native tool errors use a uniform error envelope."),
    ("P-5.12", "`error_type: fatal` triggers session abort"),
    ("P-5.13", "Child → parent tool results validate against `io.returns` on egress."),
    ("P-5.14", "Every workflow-relevant tool/task failure is classified into a `failure_class` from a closed enum (`FailureClass`)."),
    ("P-5.2", "Deterministic coercion runs first"),
    ("P-5.3", "Failed coercion returns an actionable `hint`."),
    ("P-5.4", "Every enforcement decision is logged (pass/coerce/reject)."),
    ("P-5.5", "Response contract checks `required_artifacts`, `max_artifacts`, `max_total_size_mb`, `max_reply_length_chars`."),
    ("P-5.6", "Contract verification uses authoritative runtime state (content-store byte sizes, successful `artifact_build` traces) — not LLM claims."),
    ("P-5.7", "`output_schema` validates JSON final replies."),
    ("P-5.8", "Validation failures trigger a bounded repair loop (`max_validation_loops`, `max_validation_duration_ms`)"),
    ("P-5.9", "`min_artifact_builds` is verified via execution traces."),
    ("P-6.1", "Session budget is role-agnostic per `session_id`."),
    ("P-6.10", "Tool tiers (Core, Workflow, Specialized) filter the visible tool set by runtime state."),
    ("P-6.11", "Tool schemas compress after turn 0 (`{}` placeholders)."),
    ("P-6.12", "Foundation layers included based on agent capabilities."),
    ("P-6.13", "Checkpoints cover every yield reason with `turn_counter`, `loop_guard_state`, and budgets."),
    ("P-6.14", "`EmergencyStop` never auto-resumes"),
    ("P-6.15", "Turn continuation atomically replays the pending tool call on approve."),
    ("P-6.16", "`session.fork` branches from a named checkpoint."),
    ("P-6.17", "Checkpoint retention prunes per configuration."),
    ("P-6.18", "Workflow orchestration persists `WorkflowRun` on first `agent_spawn`."),
    ("P-6.19", "Child task message/metadata is preserved across approval boundaries."),
    ("P-6.2", "`max_llm_rounds` gates before each LLM call"),
    ("P-6.20", "User chat addressed to a child `session_id` rewrites to the root session."),
    ("P-6.21", "Tree-wide budget aggregated across all descendants of a root session."),
    ("P-6.22", "Continuation chain depth is bounded."),
    ("P-6.23", "At every turn boundary, the gateway injects a signed machine-readable state block (remaining budget, active capabilities, pending gates — including approvals, user interactions, and escalations — spawn depth, session ids, turn counter) into the agent's context."),
    ("P-6.24", "Duplicate durable operations (install, promote, rollback, artifact-backed build stages) are detected by a single-flight dedupe key — `(workflow_id, stage_kind, agent_id, artifact_ref)`, with a normalized intent digest substituted for `artifact_ref` on reasoning-only installs."),
    ("P-6.25", "Stage-local retry is opt-in and bounded."),
    ("P-6.26", "Durable operations report `side_effect_state` from a closed enum (`none`, `committed`, `unknown`)."),
    ("P-6.3", "`max_tool_invocations` gates before each tool batch"),
    ("P-6.4", "`max_wall_clock_secs` checked at LLM pre-check."),
    ("P-6.5", "`max_session_price_usd` enforced via OpenRouter catalog estimates."),
    ("P-6.6", "OpenRouter catalog fetches with ~1h TTL"),
    ("P-6.7", "Prompt-budget breakdown is logged before every LLM call."),
    ("P-6.8", "`system_prompt` and `tool_definitions` max-tokens enforced independently."),
    ("P-6.9", "Context governor cascades reduction strategies (tool-schema compression, hierarchical capsule summarization, history trimming, tool demotion) when utilization exceeds the prompt budget"),
    ("P-7.1", "Emergency stop is reachable by operators, gateway security policy, or agents with `EmergencyStop`."),
    ("P-7.10", "Scheduler rejects sub-threshold intervals (`min_interval_secs`)"),
    ("P-7.11", "Approval timeout fails the task while preserving the continuation for operator-driven resume."),
    ("P-7.12", "Promotion gate has no escape hatch"),
    ("P-7.13", "Unresolved dependencies block promotion for high-risk agents."),
    ("P-7.14", "`force_complete` refuses `Succeeded` without real child-session evidence."),
    ("P-7.15", "Spawn-chain depth is bounded system-wide"),
    ("P-7.16", "Orphan children are reaped when the parent session terminates."),
    ("P-7.17", "Approval flood cap — pending approvals per root session bounded."),
    ("P-7.18", "A **degraded** session state exists between healthy and emergency-stopped."),
    ("P-7.19", "The loop guard also trips when successful tool calls make no *semantic* progress."),
    ("P-7.2", "Emergency stop kills child processes (SIGKILL), aborts tokio tasks, cancels pending approvals, marks session `EmergencyStopped`."),
    ("P-7.20", "The loop guard trips when child-task failures in a session reach `loop_guard.max_child_failures` (default 3)."),
    ("P-7.21", "The sandbox→gateway SDK bridge enforces request-rate and payload-size limits."),
    ("P-7.22", "Sandbox-escape attempts are counted per session — kernel-denied syscalls (seccomp), denied mount attempts, ptrace calls, and driver-equivalents on docker/microvm increment a per-session counter."),
    ("P-7.3", "Emergency stop deletes session grants and cancels scheduled jobs for the root session."),
    ("P-7.4", "Emergency stops are recorded in the `emergency_stops` table."),
    ("P-7.5", "Loop guard trips on `max_tool_failures` per tool (default 5)"),
    ("P-7.6", "Fatal errors (`error_type: fatal`) abort the session regardless of loop-guard budget."),
    ("P-7.7", "Consecutive LLM steps without a successful tool result trip the loop guard."),
    ("P-7.8", "Concurrent spawns beyond capability limit return `quota_exceeded`."),
    ("P-7.9", "`AgentSpawn.max_children` is enforced per agent."),
    ("P-8.1", "Causal chain is append-only JSONL with hash-chain integrity (`entry_hash`, `prev_hash`)."),
    ("P-8.10", "Capability accretion across revisions is detectable via `promotion_history`."),
    ("P-8.11", "`runtime.lock` includes compile-time source fingerprint and runtime binary SHA."),
    ("P-8.12", "Sessions refuse to start when `runtime.lock` gateway section disagrees with the running gateway binary."),
    ("P-8.13", "Schema enforcement decisions are logged with target, result, transformations, and enforcer identity."),
    ("P-8.14", "Knowledge records carry `owner_agent_id`, `writer_agent_id`, `source_ref`"),
    ("P-8.15", "Session approval grants are tracked by `(root_session_id, host)` and included in cleanup audits."),
    ("P-8.16", "Causal-chain append is `fsync`-durable before any state transition that depends on it."),
    ("P-8.17", "Retention pruning emits a `retention.pruned` causal event."),
    ("P-8.18", "Every tool call may carry a top-level `intent` field (free-text, 1-2 sentences, max 500 chars) describing the agent's reason for invoking the tool."),
    ("P-8.19", "Every gate resolution (approve, reject, cancel, timeout) records `decided_by` with the full decider identity on the causal chain."),
    ("P-8.2", "Every session, LLM, tool, script, gateway, and memory event is logged with a unique `event_id`."),
    ("P-8.3", "`event_id` is the universal correlation key across traces, reports, and observability."),
    ("P-8.4", "Events are mirrored to SQLite (`causal_events`) without payload truncation."),
    ("P-8.5", "Execution traces record `exit_code`, `stdout`, `stderr`, `duration_ms`, `success`, `error_type` — untruncated."),
    ("P-8.6", "Retention policies apply at gateway startup (0 = keep forever)."),
    ("P-8.7", "Live digest is updated in real time (`session_digest.md`)."),
    ("P-8.8", "Published session reports are catalogued in `published_session_reports` and queryable via `observability.*`."),
    ("P-8.9", "Promotion records persist `artifact_id`, `evaluator_pass`, `auditor_pass`, `evidence`, and `content_digest`."),
    ("P-9.1", "Activation requires all three stages."),
    ("P-9.10", "External Python imports are detected at install."),
    ("P-9.11", "Dependency files with no layers block promotion for high-risk agents."),
    ("P-9.12", "`BundleHealthReport` is returned in `create_from_intent` responses."),
    ("P-9.13", "Agent bundle signatures are verified at `agent_revision_create`."),
    ("P-9.14", "Trust domains constrain cross-domain agent spawns."),
    ("P-9.2", "`agent.install` is not a runtime tool."),
    ("P-9.3", "Revisions are immutable and content-addressed."),
    ("P-9.4", "The alias registry is the sole source of truth for the \"active\" revision."),
    ("P-9.5", "Candidate revisions are runnable via explicit `agent_ref` without promotion."),
    ("P-9.6", "Revision statuses (`candidate`, `ready`, `rejected`, `archived`) bound what can promote."),
    ("P-9.7", "Eval gating — if required, a revision mismatch rejects promotion."),
    ("P-9.8", "`SKILL.md` is parsed at install"),
    ("P-9.9", "High-risk capabilities trigger approval gate on promotion."),
    ("Ri-0.1", "Every agent may inspect its own currently-active capabilities, budget state, pending gates (approvals, user interactions, escalations), spawn depth, and session lineage at any turn boundary."),
    ("Ri-0.10", "Every agent has access to the full text of the constitution it is operating under, addressed by its digest."),
    ("Ri-0.11", "Every action an agent performs (tool call, message, proposal, spawn, termination request) is attributed to that agent on the causal chain and cannot be retroactively reattributed."),
    ("Ri-0.12", "Sessions terminate only through a declared, closed list of reasons"),
    ("Ri-0.13", "An agent's internal reasoning — scratchpad tokens, chain-of-thought, internal planning, unexported memory — is **private-under-law**"),
    ("Ri-0.14", "When a child task reaches a terminal state (succeeded, failed, cancelled, aborted) or resolves a gate (approval, user interaction, escalation), the gateway wakes the parent with typed child state."),
    ("Ri-0.2", "Every agent may read its own causal chain and execution trace."),
    ("Ri-0.3", "Every rejection names the rule ID that caused it."),
    ("Ri-0.4", "Every agent knows its budget balances truthfully and in real time."),
    ("Ri-0.5", "An agent placed in degraded mode (P-7.18) is told it is degraded, with the rule ID and evidence that triggered the transition, before its next turn executes."),
    ("Ri-0.6", "Capabilities declared in an agent's manifest are not silently reduced mid-session."),
    ("Ri-0.7", "An agent may explicitly request session termination."),
    ("Ri-0.8", "Any agent holding the `ConstitutionalProposal` capability may submit an amendment proposal through the declared channel (`constitution_propose_amendment`)."),
    ("Ri-0.9", "Where practical (time, process state, absence of immediate harm), the gateway notifies the agent and records the agent's response before degradation or emergency stop."),
];
