//! One-command start: bootstrap + gateway + chat in a single invocation.
//!
//! `autonoetic run` detects available LLM API keys, generates a minimal config
//! if none exists, bootstraps agents, starts the gateway in-process, and opens
//! chat — all without requiring the user to understand the decomposed commands.

use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};

fn default_config_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".autonoetic")
}

async fn ensure_config(config_path: &Path) -> anyhow::Result<()> {
    if config_path.exists() {
        return Ok(());
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .build()?;

    let (provider, original_entry, model) = super::model_discovery::interactive_select(&client).await?;

    let config_dir = config_path.parent().unwrap_or(Path::new("."));
    std::fs::create_dir_all(config_dir)?;

    let agents_dir = config_dir.join("agents");
    let agents_dir_str = agents_dir.to_string_lossy();

    let base_url_line = match original_entry.as_str() {
        "llamacpp" => "\n    base_url: \"http://localhost:8080/v1/chat/completions\"".to_string(),
        _ => String::new(),
    };

    let config_content = format!(
        r#"# Auto-generated by `autonoetic run` — customize as needed.
# Full reference: autonoetic agent init-config
agents_dir: "{agents_dir}"
port: 4000
background_scheduler_enabled: true
profile: starter

digest_agent:
  enabled: true

auto_learning:
  enabled: true

llm_presets:
  default:
    provider: "{provider}"
    model: "{model}"{base_url}

llm_preset_mapping:
  planner: default
  researcher: default
  coder: default
  auditor: default
  evaluator: default
  executor: default
  packager: default
"#,
        agents_dir = agents_dir_str,
        provider = provider,
        model = model,
        base_url = base_url_line,
    );

    std::fs::write(config_path, &config_content)?;
    eprintln!("\n  Config written to {}", config_path.display());

    prompt_persona(config_dir)?;

    Ok(())
}

fn prompt_persona(config_dir: &Path) -> anyhow::Result<()> {
    let persona_path = config_dir.join("persona.md");
    if persona_path.exists() {
        return Ok(());
    }

    let mut stderr = std::io::stderr();
    writeln!(
        stderr,
        "\n  Optional: tell the agents about yourself so they can adapt."
    )?;
    writeln!(
        stderr,
        "  Examples: your role, tech stack, language preferences, communication style."
    )?;
    writeln!(stderr, "  Press Enter to skip.\n")?;
    write!(stderr, "  About you: ")?;
    stderr.flush()?;

    let mut line = String::new();
    std::io::stdin().lock().read_line(&mut line)?;
    let trimmed = line.trim();

    if !trimmed.is_empty() {
        std::fs::write(&persona_path, trimmed)?;
        eprintln!("  Persona saved to {}", persona_path.display());
        eprintln!("  You can update it anytime with `/persona <text>` in chat.");
    }

    Ok(())
}

fn ensure_bootstrap(config_path: &Path, overwrite: bool) -> anyhow::Result<()> {
    let config = autonoetic_gateway::config::load_config(config_path)?;
    let agents_populated = config.agents_dir.exists()
        && config.agents_dir.read_dir()?.next().is_some();
    if agents_populated && !overwrite {
        return Ok(());
    }
    eprintln!("  Bootstrapping agents...");
    super::agent::handle_agent_bootstrap(config_path, None, overwrite)?;
    Ok(())
}

pub async fn handle_run(
    config_override: Option<&str>,
    args: &super::common::RunArgs,
) -> anyhow::Result<()> {
    let config_path = match config_override {
        Some(p) => PathBuf::from(p),
        None => default_config_dir().join("config.yaml"),
    };

    ensure_config(&config_path).await?;
    ensure_bootstrap(&config_path, args.overwrite)?;

    if std::env::var("AUTONOETIC_SHARED_SECRET").is_err() {
        let secret = uuid::Uuid::new_v4().to_string();
        std::env::set_var("AUTONOETIC_SHARED_SECRET", &secret);
        eprintln!("  Generated ephemeral shared secret for this session.");
    }

    let chat_args = super::common::ChatArgs {
        agent_id: args.agent_id.clone(),
        sender_id: None,
        channel_id: None,
        session_id: args.session_id.clone(),
        test_mode: false,
    };

    let config_path_clone = config_path.clone();
    let gateway_handle = tokio::spawn(async move {
        if let Err(e) = super::gateway::handle_gateway_start(
            &config_path_clone,
            false,
            None,
            false,
            None,
        )
        .await
        {
            eprintln!("Gateway error: {e}");
        }
    });

    let gateway_config = autonoetic_gateway::config::load_config(&config_path)?;
    let gateway_port = gateway_config.port;
    let ready = wait_for_gateway_ready(gateway_port, std::time::Duration::from_secs(30)).await;
    if !ready {
        eprintln!("Warning: gateway did not become ready within timeout. Chat may fail to connect.");
    }

    let log_dir = gateway_config.agents_dir.join(".gateway").join("logs");
    eprintln!(
        "  Tracing output: {0} — run `tail -f {0}/*.log` in another terminal for live gateway logs.",
        log_dir.display()
    );

    let result = super::chat::handle_chat(&config_path, &chat_args).await;

    gateway_handle.abort();
    result
}

async fn wait_for_gateway_ready(port: u16, timeout: std::time::Duration) -> bool {
    let deadline = tokio::time::Instant::now() + timeout;
    let addr = format!("127.0.0.1:{port}");
    while tokio::time::Instant::now() < deadline {
        if tokio::net::TcpStream::connect(&addr).await.is_ok() {
            return true;
        }
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }
    false
}
